---

- name: Create users
  hosts: "{{ groups.all }}"
  vars_files: 
    - vars/common/users.yaml
  roles:
    - role: create-user
      become: true
  tags: 
    - user

- name: Configure ssh related settings
  hosts: "{{ groups.all }}"
  any_errors_fatal: true
  roles:
    - role: push-ssh-keys
  tags:
    - ssh

- name: Install Homebrew 
  hosts: "{{ groups.all }}"
  roles:
    - role: homebrew
  tags:
    - homebrew

- name: Install command line tools that boost developer productivity 
  hosts: "{{ groups.all }}"
  roles:
    - role: common-cli
  tags:
    - cli

- name: Setup Zsh
  hosts: "{{ groups.all }}"
  roles:
    - role: setup-zsh
  tags:
    - zsh