---

- name: Update docker-compose.yaml
  hosts: "{{ groups.staging }}"
  become: true
  any_errors_fatal: true
  vars_files: 
    - vars/deployment/vars-for-docker-compose.yaml
  roles:
    - role: docker-compose
  tags:
    - docker-compose

- name: Deploy service1  
  hosts: "{{ groups.staging_service1 }}"
  become: true
  any_errors_fatal: true
  vars_files:
    - vars/deployment/vars-for-docker-compose.yaml
  roles:
    - service1  
  tags:
    - service1