---
- name: Update docker-compose.yaml
  hosts: "{{ groups.staging }}"
  any_errors_fatal: true
  vars_files:
    - vars/deployment/env.example.yaml
  roles:
    - role: docker-compose
  tags:
    - docker-compose

- name: Deploy service1
  hosts: "{{ groups.staging_service1 }}"
  any_errors_fatal: true
  vars_files:
    - vars/deployment/env.example.yaml
  roles:
    - service1
  tags:
    - service1
