---

- name: Install docker engine and docker-compose
  hosts: "{{ groups.all }}"
  roles:
    - role: evanhongo.docker
  tags:
    - docker

- name: Install helm
  hosts: "{{ groups.all }}"
  roles:
    - role: gantsign.helm
      vars:
        helm_version: 3.13.0
        helm_architecture: amd64
  tags:
    - helm