---
- name: Install Homebrew
  hosts: "{{ groups.all }}"
  tasks:
    - shell: "/bin/bash -c $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  tags:
    - homebrew

- name: Install command line tools that boost developer productivity
  hosts: "{{ groups.all }}"
  tasks:
    - community.general.homebrew:
      name: tmux,commitizen,exa,bat,fd,the_silver_searcher,htop,jq,thefuck,fzf,httpie,lazydocker,yt-dlp,cmatrix
      state: present
  tags:
    - cli

- name: Setup Zsh
  hosts: "{{ groups.all }}"
  roles:
    - role: setup-zsh
  tags:
    - zsh
