---

- name: Make sure "{{ docker_deploy_base_dir }}" exists
  file:
    path: "{{ docker_deploy_base_dir }}"
    state: directory

- name: Copy docker-compose.yaml
  template:
    backup: yes
    src: "docker-compose.{{ ENV }}.yml"
    dest: "{{ docker_deploy_base_dir }}/docker-compose.yaml"
    mode: '0777'
